name: super_simple_authentication_flutter
description: A Flutter client for Super Simple Authentication.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  api_client:
    path: ../../api_client
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  shared_authentication_objects:
    path: ../super_simple_authentication_server/packages/shared_authentication_objects

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
