name: super_simple_authentication_flutter
description: A Flutter client for Super Simple Authentication.
version: 0.0.1-dev.1
repository: https://github.com/mtwichel/super_simple_flutter_authentication/tree/main/packages/super_simple_authentication_flutter

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
