name: super_simple_authentication_server
description: The server for Super Simple Authentication.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  dart_frog: ^1.1.0
  equatable: ^2.0.7
  hive_ce: ^2.11.3
  http: ^1.4.0
  json_annotation: ^4.9.0
  meta: ^1.16.0
  pointycastle: ^4.0.0
  postgres: ^3.5.6
  postgres_builder: ^2.5.0
  super_simple_authentication_toolkit:
    path: ../super_simple_authentication_toolkit
  uuid: ^4.5.1

dev_dependencies:
  json_serializable: ^6.9.5
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^6.0.0
