name: super_simple_authentication_server
description: The server for Super Simple Authentication.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  dart_frog: ^1.1.0
  super_simple_authentication_hive_data_storage:
    path: ../super_simple_authentication_hive_data_storage
  super_simple_authentication_postgres_data_storage:
    path: ../super_simple_authentication_postgres_data_storage
  super_simple_authentication_toolkit: ^0.0.1-dev.1

dev_dependencies:
  json_serializable: ^6.9.5
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^6.0.0
