name: Security Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Set image tag for scanning
        id: scan-tag
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "tag=security-scan:pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
          else
            echo "tag=security-scan:${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Build Docker image for scanning
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          platforms: linux/amd64
          push: false
          tags: ${{ steps.scan-tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.scan-tag.outputs.tag }}
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"
        continue-on-error: true

      - name: Check if SARIF file exists
        id: check-sarif
        run: |
          if [ -f "trivy-results.sarif" ]; then
            echo "file-exists=true" >> $GITHUB_OUTPUT
            echo "✅ Trivy SARIF file found"
          else
            echo "file-exists=false" >> $GITHUB_OUTPUT
            echo "⚠️  Trivy SARIF file not found - creating empty one"
            echo '{"version":"2.1.0","$schema":"https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json","runs":[{"tool":{"driver":{"name":"trivy","version":"0.0.0"}},"results":[]}]}' > trivy-results.sarif
          fi

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

  docker-scout-scan:
    name: Docker Scout Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Set image tag for scanning
        id: scan-tag
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "tag=scout-scan:pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
          else
            echo "tag=scout-scan:${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Build Docker image for scanning
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          platforms: linux/amd64
          push: false
          tags: ${{ steps.scan-tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

      - name: Run Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ steps.scan-tag.outputs.tag }}
          sarif-file: docker-scout-results.sarif
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Check if Docker Scout SARIF file exists
        id: check-scout-sarif
        run: |
          if [ -f "docker-scout-results.sarif" ]; then
            echo "file-exists=true" >> $GITHUB_OUTPUT
            echo "✅ Docker Scout SARIF file found"
          else
            echo "file-exists=false" >> $GITHUB_OUTPUT
            echo "⚠️  Docker Scout SARIF file not found - creating empty one"
            echo '{"version":"2.1.0","$schema":"https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json","runs":[{"tool":{"driver":{"name":"docker-scout","version":"0.0.0"}},"results":[]}]}' > docker-scout-results.sarif
          fi

      - name: Upload Docker Scout results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: docker-scout-results.sarif
