name: Super Simple Authentication Flutter Verify and Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/super_simple_authentication_flutter_verify_and_test.yaml"
      - "super_simple_authentication_flutter/**"
      - "super_simple_authentication_server/packages/shared_authentication_objects/**"
  push:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/**"
      - "super_simple_authentication_flutter/**"
      - "super_simple_authentication_server/packages/shared_authentication_objects/**"

jobs:
  verify_and_test:
    name: Verify and Test
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@main
    with:
      working_directory: super_simple_authentication_flutter
      min_coverage: 0
      flutter_channel: stable
      flutter_version: 3.29.0
