name: super_simple_authentication_server
description: The server for Super Simple Authentication.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  cryptography: ^2.7.0
  dart_frog: ^1.1.0
  equatable: ^2.0.7
  http: ^1.4.0
  json_annotation: ^4.9.0
  meta: ^1.16.0
  pointycastle: ^4.0.0
  postgres: ^3.5.6
  postgres_builder: ^2.1.0
  shared_authentication_objects:
    path: packages/shared_authentication_objects

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
